default_install_hook_types = ["pre-commit", "commit-msg"]

[[repos]]
repo = "https://github.com/jorisroovers/gitlint"
rev = "v0.19.1"
hooks = [
  { id = "gitlint", stages = ["commit-msg"], args = ["--msg-filename"] },
]
[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.11"
hooks = [
  { id = "actionlint" },
]
[[repos]]
repo = "builtin"
hooks = [
  { id = "check-symlinks" },
  { id = "check-toml" },
  { id = "end-of-file-fixer" },
  { id = "no-commit-to-branch" }, # Prevent committing to protected branches
]
